### ISSUE TITLE
Pan/Tilt with OpenIPC and the tapo-c210

### ISSUE THREAD

**Issue by BRFud** [xfarrow/tapo-camera#2]
Thanks for this info on the Tapo C210! Just wondering if you have any information about the possibility to control the Pan/Tilt function of the C210 after flashing OpenIPC to it?

**Comment by ferrum** [comment]
Hi! I have not tested it yet (I don't have all the required hardware) so I can't tell, but according to the [specifications](https://linux-chenxing.org/infinity6/ssc335_pb_v03.pdf) (page 7) the pan/tilt motor is controller by the processor itself and not by an external module. OpenIPC's [website](https://openipc.org/cameras/vendors/sigmastar/socs/ssc335) states that the development has completed for our platform. This would lead me to think that OpenIPC can control that motor but again, it's only a supposition.

If you will ever try, please let us know your impressions.
